language: node_js
node_js: lts/*
branches:
  only:
    - master
before_script:
- rm -rf ./node_modules package-lock.json
script: echo “Deploy!!”
install: npm install -g firebase-tools && npm --prefix hosting install --no-optional
after_success: firebase deploy --only hosting --project andor-pwa